Added setting of hostname in local.conf and added dunfel compatibilit…
MistySOM/rzv2l pull request #20
Opened 2023-05-30 14:49 UTC by mistyron

Set hostname in `local.conf` from `start.sh` and 
* add dunfell compatibility to layers where they're missing to avoid WARNING - copied from rzg2l container

2023-05-30 15:29 UTC, matinlotfali reviewed
See my comment

2023-05-30 15:29 UTC, matinlotfali commented on Build/start.sh
> +    'cd ${YOCTODIR}'
Probably don't need to change this. It is inside echo

2023-05-30 18:18 UTC, matinlotfali requested changes
Please update the submodule to the latest develop commit

2023-05-30 20:28 UTC, matinlotfali commented
@mistyron This is the first appearance of enable-phy in rzg2l.
Looks like when you create a patch file, you need to apply the patch 0001 first and then create your own patch on top of it.

2023-06-04 03:49 UTC, matinlotfali commented
@mistyron Please update the submodule to the latest develop commit again

2023-06-04 04:16 UTC, mistyron commented
> @mistyron Please update the submodule to the latest develop commit again

done

2023-06-04 06:20 UTC, matinlotfali approved these changes

2023-06-04 07:28 UTC, merged