Drpai translator
MistySOM/rzv2l pull request #75
Opened 2024-07-23 08:20 UTC by mistyron

Added drpai-translator container image

2024-07-23 18:39 UTC, mistyron commented
> Each time these files are changed, the RZV2L images will be built which is unrelated to the contents of these files. So I think this folder should become a separate repository and it should have a different CI/CD.

I see what you are saying and don't diagree! The initial idea was tohave various directories & containers in this repo (hence the `Build/`). Things have developed since the initial idea :)

2024-07-23 20:31 UTC, matinlotfali commented
> The initial idea was to have various directories & containers in this repo

So I suggest we limit the current GitHub Actions to the `build/` directory. This means if files outside of the directory has changed, it won't run it.

2024-07-24 09:53 UTC, mistyron commented
> > The initial idea was to have various directories & containers in this repo
> 
> So I suggest we limit the current GitHub Actions to the `build/` directory. This means if files outside of the directory has changed, it won't run it.

Yes, I agree with that!

2024-07-24 14:47 UTC, matinlotfali commented
Your finding is correct and I agree.

2024-07-24 14:57 UTC, mistyron commented
> Your finding is correct and I agree.

Okay, I have gone ahead and updated the `yml` files accordingly. I'm not exactly sure how to verify and test the changes though.

2024-07-24 15:09 UTC, matinlotfali commented
I think they should be capital B.
Linux directories are case-sensitive.

2024-07-24 15:16 UTC, mistyron commented
> I think they should be capital B. Linux directories are case-sensitive.

DUH, of course! Good catch! I'll fix!

2024-07-24 15:24 UTC, mistyron commented
> I think they should be capital B. Linux directories are case-sensitive.

Give it another look when you can!

2024-07-24 15:55 UTC, matinlotfali requested changes
I think some of the GitHub Actions are suitable for the whole repository. Only two of them are specific to the Build directory.

2024-07-24 15:55 UTC, matinlotfali commented on .github/workflows/release-submission.yml
> +        paths: [ "Build/**" ]
I think this one can be non-specific for directories

2024-07-24 15:55 UTC, matinlotfali commented on .github/workflows/master-merge.yml
> +    paths: [ "Build/**" ]
I think this one can be non-specific for directories

2024-07-24 15:55 UTC, matinlotfali commented on .github/workflows/develop-ff.yml
> +    paths: [ "Build/**" ]
I think this one can be non-specific for directories

2024-07-24 15:55 UTC, matinlotfali commented on .github/workflows/create-pull-request.yml
> +    paths: [ "Build/**" ]
I think this one can be non-specific for directories

2024-07-24 17:52 UTC, mistyron commented
> I think some of the GitHub Actions are suitable for the whole repository. Only two of them are specific to the Build directory.

Oh, I assumed all the workflows would be for stuff in `Build/` only - but I've now changed the `yml`s accordingly

2024-07-24 18:20 UTC, matinlotfali approved these changes
It looks good now

2024-07-30 15:46 UTC, merged